import { prisma } from "../lib/prisma";

export type ExportFormat = "markdown" | "html" | "jsonld";

export interface ExportResult {
  filename: string;
  contentType: string;
  content: string;
}

export class ReportExportService {
  /**
   * Main export method generating structured documents in Markdown, HTML, or JSON-LD format.
   */
  public static async exportReport(
    sessionId: string,
    userId: string,
    format: ExportFormat = "markdown"
  ): Promise<ExportResult | null> {
    const session = await prisma.researchSession.findUnique({
      where: { id: sessionId },
      include: {
        reports: { orderBy: { createdAt: "desc" }, take: 1 },
        claims: true,
        evidence: { include: { source: true } },
        sources: true,
      },
    });

    if (!session || session.userId !== userId) {
      return null;
    }

    const latestReport = session.reports[0];
    const reportTitle = latestReport?.title || session.title;
    const reportContent = latestReport?.content || `Research investigation into: ${session.query}`;

    switch (format) {
      case "html":
        return {
          filename: `scout-report-${sessionId}.html`,
          contentType: "text/html; charset=utf-8",
          content: this.exportHTML(session.title, reportTitle, reportContent, session.sources, session.evidence),
        };
      case "jsonld":
        return {
          filename: `scout-report-${sessionId}.json`,
          contentType: "application/ld+json; charset=utf-8",
          content: this.exportJSONLD(session.title, reportTitle, reportContent, session.sources, session.claims),
        };
      case "markdown":
      default:
        return {
          filename: `scout-report-${sessionId}.md`,
          contentType: "text/markdown; charset=utf-8",
          content: this.exportMarkdown(session.title, reportTitle, reportContent, session.sources, session.evidence),
        };
    }
  }

  /**
   * Generates Markdown document with inline citation superscripts and Bibliography reference tree.
   */
  public static exportMarkdown(
    sessionTitle: string,
    reportTitle: string,
    rawContent: string,
    sources: any[],
    evidence: any[]
  ): string {
    const sourceMap = new Map<string, { index: number; url: string; title: string; publisher?: string }>();
    sources.forEach((src, idx) => {
      sourceMap.set(src.id, {
        index: idx + 1,
        url: src.url,
        title: src.title,
        publisher: src.publisher || undefined,
      });
    });

    let formattedContent = rawContent;
    evidence.forEach((ev) => {
      const srcInfo = sourceMap.get(ev.sourceId);
      if (srcInfo && ev.content && formattedContent.includes(ev.content.substring(0, 30))) {
        formattedContent = formattedContent.replace(
          ev.content,
          `${ev.content} [<sup>${srcInfo.index}</sup>](${srcInfo.url})`
        );
      }
    });

    const bibliography = sources
      .map((src, idx) => {
        const publisherStr = src.publisher ? ` *${src.publisher}*.` : "";
        return `${idx + 1}. [${src.title}](${src.url})${publisherStr} (Accessed: ${new Date(
          src.createdAt
        ).toLocaleDateString()})`;
      })
      .join("\n");

    return `# 🔎 SCOUT Research Intelligence Report

## ${reportTitle}

> **Original Query:** ${sessionTitle}  
> **Generated Date:** ${new Date().toUTCString()}  

---

### Executive Summary & Findings

${formattedContent}

---

### 📚 Bibliography & Evidence Reference Tree

${sources.length > 0 ? bibliography : "_No external web sources linked._"}

---
*Report generated by SCOUT Multi-Agent Research Platform.*
`;
  }

  /**
   * Generates styled HTML document with typography and footnote references.
   */
  public static exportHTML(
    sessionTitle: string,
    reportTitle: string,
    rawContent: string,
    sources: any[],
    evidence: any[]
  ): string {
    const markdownStr = this.exportMarkdown(sessionTitle, reportTitle, rawContent, sources, evidence);
    const htmlBody = markdownStr
      .replace(/^# (.*$)/gim, '<h1 className="title">$1</h1>')
      .replace(/^## (.*$)/gim, '<h2>$1</h2>')
      .replace(/^### (.*$)/gim, '<h3>$1</h3>')
      .replace(/^\> (.*$)/gim, '<blockquote>$1</blockquote>')
      .replace(/\n\n/g, '<p></p>');

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${reportTitle} - SCOUT Intelligence Report</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; max-width: 800px; margin: 40px auto; padding: 0 20px; color: #1e293b; line-height: 1.6; }
    h1 { color: #0f172a; border-bottom: 2px solid #e2e8f0; padding-bottom: 10px; }
    h2 { color: #1e293b; margin-top: 30px; }
    blockquote { background: #f8fafc; border-left: 4px solid #3b82f6; margin: 20px 0; padding: 12px 20px; font-style: italic; }
    a { color: #2563eb; text-decoration: none; }
    a:hover { text-decoration: underline; }
    hr { border: 0; border-top: 1px solid #e2e8f0; margin: 30px 0; }
    .footer { font-size: 12px; color: #64748b; margin-top: 40px; text-align: center; }
  </style>
</head>
<body>
  ${htmlBody}
  <div class="footer">Report generated by SCOUT Multi-Agent Research Engine</div>
</body>
</html>`;
  }

  /**
   * Generates Schema.org ScholarlyArticle JSON-LD format.
   */
  public static exportJSONLD(
    sessionTitle: string,
    reportTitle: string,
    rawContent: string,
    sources: any[],
    claims: any[]
  ): string {
    const jsonLdGraph = {
      "@context": "https://schema.org",
      "@type": "ScholarlyArticle",
      headline: reportTitle,
      name: reportTitle,
      about: sessionTitle,
      datePublished: new Date().toISOString(),
      author: {
        "@type": "Organization",
        name: "SCOUT Multi-Agent Research Platform",
      },
      articleBody: rawContent,
      citation: sources.map((src) => ({
        "@type": "WebPage",
        name: src.title,
        url: src.url,
        publisher: src.publisher || undefined,
      })),
      hasPart: claims.map((c) => ({
        "@type": "Claim",
        text: c.content,
        claimInterpreter: {
          "@type": "Organization",
          name: "SCOUT Critic & Verification Scout",
        },
      })),
    };

    return JSON.stringify(jsonLdGraph, null, 2);
  }
}
